//Get vote salon for Salon owner
export const GET_VOTE_FOR_SALON_SUCCESSFULLY =
  "GET_VOTE_FOR_SALON_SUCCESSFULLY";
export const GET_VOTE_FOR_SALON_FAILED = "GET_VOTE_FOR_SALON_FAILE";

export const RESET_VOTE_OF_SALON = "RESET_VOTE_OF_SALON";

//Get reviews salon for Salon owner
export const GET_REVIEW_FOR_SALON_SUCCESSFULLY =
  "GET_REVIEW_FOR_SALON_SUCCESSFULLY";
export const GET_REVIEW_FOR_SALON_FAILED = "GET_REVIEW_FOR_SALON_FAILED";

export const RESET_REVIEW_OF_SALON = "RESET_REVIEW_OF_SALON";

//Add feedback for salon by customer
export const ADD_FEEDBACK_FAILED =
"ADD_FEEDBACK_FAILED";
export const ADD_FEEDBACK_SUCCESSFULLY = "ADD_FEEDBACK_SUCCESSFULLY";