//Get vote salon for Salon owner
export const GET_VOTE_FOR_SALON_SUCCESSFULLY =
  "GET_VOTE_FOR_SALON_SUCCESSFULLY";
export const GET_VOTE_FOR_SALON_FAILED = "GET_VOTE_FOR_SALON_FAILE";

//Get reviews salon for Salon owner
export const GET_REVIEW_FOR_SALON_SUCCESSFULLY =
  "GET_REVIEW_FOR_SALON_SUCCESSFULLY";
export const GET_REVIEW_FOR_SALON_FAILED = "GET_REVIEW_FOR_SALON_FAILED";